dns-violations/dnsflagday

- README.md
I tried to help clean up some of the grammar to make the main text of the project a bit better grammatically.
> grammatical improvements

- es/README.md
Created "es" subdir with spanish translation. Thanks.
> Spanish translation.

- es/README.md
Added JS form to ednscomp API for domain owners, plus some minor changes in "es" translation.
> Keeping up with last upstream changes

- es/README.md
> Contact section translation to es

- es/README.md
> New messages for check site owners.

- es/README.md
> New site logo

- es/README.md
Hi. I don't know if you allow this split from the main english text, but it would be very beneficial for our community to have this material in spanish!
Thanks.
> New presentation item in spanish language.

- README.md
- cs/README.md
- es/README.md
- flags/pt-br.svg
- pt-br/README.md
It's missing the Brazilian flag because I couldn't find where the existing SVG flags came from. Please let me know and I can update this PR with it.
> Add Brazilian Portuguese (pt-BR) translation

- README.md
- cs/README.md
@pspacek I wrote down 3.3.0 which is not entirely correct - can you propose (or push) better text?
> add resolver version list

- pt-br/README.md
Anchor is in brazilian portuguese, but link still in english
> Fix link anchor in Portuguese translation

- es/README.md
- New firewalls section
- Updated URLs
- New comment for github warning
> Syncing es translation + warning for markdown

- _config.yml
- robots.txt
I think this may be beneficial with SEO as there are multiple pages /
language versions.
> Add sitemap.xml generation & robots.txt

- index-cs.md
- index.md
An friendly copyeriter recommended couple changes to make site more
useful for non-experts. Comments are welcome!
> Site overhaul

- _data/checker.yml
- _includes/checker.html
Texts were split into bullet points to make it easier to digest.
Further improvements should be made to non-www hints etc.
> re-texting test results for layman

- _data/checker.yml
Translation of changes as requested in #63
> Translation of changes to pt-br as requested

- _data/checker.yml
update errorBan & rateLimit section for checker.yml to fit Simplified Chinese.
> update Simplified Chinese text for checker.yml

- index-cs.md
- index-es.md
- index-ru.md
- index-zh-CN.md
- index.md
add a link to the article on dns flag day and support information from efficient iP
> add efficient iP vendor link

- index-pt-br.md
I still want to check the texts in `_data`. Will let you know when it's ready to merge.
> Fixed some pt-br misspells

- index.md
- Add information that DNS flag day is community driven and where technical discussions can be made
> Who's behind, tech mailing list

- 2020/index.md
- 2020/tester.md
- Try and force build of 2020 directory
> 2020 index

- _data/2020_checker.yml
- _includes/2020_checker.html
- js/tcp-checker.js
It follows methodology described in
https://gitlab.labs.nic.cz/knot/edns-zone-scanner/blob/master/doc/methodology_tcp.rst
> Tester for DNS flag day 2020

- 2020/index-fr.md
- 2020/index.md
- _data/2020_checker.yml
- _includes/2020_languages.html
- Add French translation by @ncartron
> French translation

- 2020/index-es.md
- 2020/index.md
- _data/2020_checker.yml
- _includes/2020_languages.html
Hi. Just as I did for the 2019 campaign, here is the "es" translation for the 2020 site. Thanks.
> Spanish translation

- 2020/index-zh-CN.md
- 2020/index.md
- _data/2020_checker.yml
- _includes/2020_languages.html
I translated index.md into Chinese Version index-zh-CN.md. I also translate 2020_checker.yml with a cn entry.
> Chinese Version of index.md

- _includes/2020_supporters.html
- Fix supporter generation and randomizing by adding an empty dummy if the number of supporters are odd
> Supporters

- 2020/index-es.md
- 2020/index-fr.md
- 2020/index-ja.md
- 2020/index-zh-CN.md
- 2020/index.md
- _data/2020_checker.yml
- _includes/2020_cli_checker.html
- _layouts/default.html
- js/client-tcp-checker.js
- Add client TCP checker
- Add a network check before starting the client TCP check
- Copy the English text to all languages
- Add checker to all languages
> Client TCP checker

- _data/2020_checker.yml
- Sync changes made by @pspacek on `en`
> client TCP checker text

- 2020/index-es.md
- _data/2020_checker.yml
> Syncing es translation to new client-tcp code

- 2020/index-ja.md
- _data/2020_checker.yml
I translated Client TCP checker which is added in #123 into Japanese.
Please feel free to use it.
> Japanese translation: Client TCP checker

- js/client-tcp-checker.js
- Use `https://` for client TCP checker
> 2020 tcp https

- 2020/index-fr.md
> updated French translation

- 2020/index.md
> add reference to fujiwara draft and date issue.

- 2020/index.md
- replace all occurences of "date-to-be-decided"
and repeat The Date couple more times
- move historical data to the end of page
- link to measurement results by Google
> 2020: clarification, cleanup

- 2020/index-ja.md
- _data/2020_checker.yml
I updated Japanese translation to reflect the recent changes in #133, #140 and #142.
Please feel free to use it.
> Japanese Translation: #133, #140, #142 and #144
